#!/bin/bash
set -o pipefail
exitcode=0
while [ "$1" ]; do
    ( mpg123 --wav /dev/stdout "$1" | lame -b 256 - "${1}.new" && mv -fv "${1}.new" "${1}" ) || (exitcode=1)
    shift
done
echo -e '\nConcluido.'
exit $exitcode

