#!/bin/bash
exitcode=0
while [ "$1" ]; do
    ( ogg123 -d wav -f /dev/stdout "$1" | lame -b 256 - "`dirname \"$1\"`/`basename \"$1\" '.ogg'`.mp3" ) || (exitcode=1)
    shift
done
echo -e '\nConcluido.'
exit $exitcode

