#!/bin/bash
set -o pipefail
echo -n "Qualidade: "
read qualidade
exitcode=0
while [ "$1" ]; do
    if ( mpg123 --wav /dev/stdout "${1}" | lame -b "$qualidade" - "${1}-${qualidade}kbps.mp3" ); then
        if [ "`stat -c '%s' \"${1}\"`" -lt "`stat -c '%s' \"${1}-${qualidade}kbps.mp3\"`" ]; then
            cp -fv "${1}" "${1}-${qualidade}kbps.mp3"
        fi
    else
        exitcode=1
        rm -f "${1}-${qualidade}kbps.mp3"
    fi
    shift
done
echo -e '\nConcluido.'
exit $exitcode

